name: Dev Deploy

on:
  # This is the 'dev' configuration
  workflow_dispatch:
  # trigger on push to main
  push:
    branches:
      - main
    paths:
      - 'configurations/dev/config-dev-manifest.json'      

permissions:
  actions: write
  
jobs:
  read-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      
      - name: Install gh extension 'thetechcollective/rotator'
        # Visit https://github.com/thetechcollective/gh-rotator for more information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          command -v python3 || { echo "Python3 is not installed"; exit 1; }
          gh extension install thetechcollective/gh-rotator

      - name: Read the manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          MANIFEST=$(gh rotator manifest --configuration dev)
          echo '```json'    >> $GITHUB_STEP_SUMMARY
          echo "$MANIFEST"  >> $GITHUB_STEP_SUMMARY
          echo '```'        >> $GITHUB_STEP_SUMMARY

