#!/usr/bin/env bash

# Function to check if python is installed
ensure_python3() {
    if ! command -v python3 &> /dev/null; then
        echo "Python3 not found. Please install Python3."
        exit 1
    fi
}

# Execute the Python script directly
ensure_python3
python3 $(dirname "$0")/gh_rotator/gh_rotator.py "$@"
